// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ZupaTechTest.Data;

namespace ZupaTechTest.Data.Migrations
{
    [DbContext(typeof(BookingContext))]
    [Migration("20181205232653_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ZupaTechTest.Data.MeetingSlot", b =>
                {
                    b.Property<Guid>("MeetingSlotId")
                        .ValueGeneratedOnAdd();

                    b.HasKey("MeetingSlotId");

                    b.ToTable("MeetingSlots");
                });

            modelBuilder.Entity("ZupaTechTest.Data.SeatBooking", b =>
                {
                    b.Property<Guid>("SeatBookingId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email");

                    b.Property<Guid>("MeetingSlotId");

                    b.Property<string>("Name");

                    b.Property<string>("SeatNumber");

                    b.HasKey("SeatBookingId");

                    b.HasIndex("MeetingSlotId");

                    b.ToTable("SeatBookings");
                });

            modelBuilder.Entity("ZupaTechTest.Data.SeatBooking", b =>
                {
                    b.HasOne("ZupaTechTest.Data.MeetingSlot", "MeetingSlot")
                        .WithMany("SeatBookings")
                        .HasForeignKey("MeetingSlotId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
